apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: app-of-apps-example-tree
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://github.com/argocd-training/example-tree.git
    targetRevision: HEAD
    path: apps/
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
