apiVersion: v1
kind: Pod
metadata:
  name: foo
spec:
  containers:
    - name: main
      image: ondrejsika/training-example:ondrejsika
      resources:
        requests:
          cpu: 10m
          memory: 15Mi
        limits:
          cpu: 10m
          memory: 15Mi
